### ISSUE TITLE
Support for Vite 4

### ISSUE THREAD

**Issue by mgruhn** [Modyfi/vite-plugin-yaml#10]
[Vite 4](https://vitejs.dev/blog/announcing-vite4.html) has been out for a couple of weeks. I've tested a bit and had no problems with the plugin on this version, so support may just involve updating the peerDependency versions.

**Comment by iBobik** [comment]
Seems working in my project, just suppress that error:
```
npm install -D @modyfi/vite-plugin-yaml -f
```

**Comment by tonyketcham** [comment]
Vite v4 is now supported in `v1.0.4`!
