### ISSUE TITLE
Fails while loading yaml with numeric keys

### ISSUE THREAD

**Issue by isahohieku** [Modyfi/vite-plugin-yaml#20]
Hi!

I currently work on a project with translations in yml.

We manage errors by assigning numeric codes to them which we use as keys. E.g 
`"000": System error`

But I get the error:
`Octal literals are not allowed in strict mode.`

After searching hard, I realised that JS was having issues with having numeric keys with leading zeros in an object while using strict mode.

Searching further, I also confirmed it because of the use of the package `tosource`.

Duplicating the code and replacing the line where `tosource` was used solved my problem.

Hence I propose that we should also allow for use of `raw` option if it works in some cases.

With the right permissions, I can create a PR of a solution.

**Comment by tonyketcham** [comment]
Thanks for contributing this issue! We'd gladly welcome a PR adding this option 👍 

You should be able to fork this repo and create a PR from it
