### ISSUE TITLE
Support Vite 5.0

### ISSUE THREAD

**Issue by undergroundwires** [Modyfi/vite-plugin-yaml#22]
Hi,

First of all thank you for this super easy-to-use plugin. It has been a joy to use it without any issues and it empowers builds of [privacy.sexy](https://github.com/undergroundwires/privacy.sexy).

Vite 5 is [released](https://vitejs.dev/guide/migration.html) and this package requires maximum of Vite 4.x as peer-dependency.

Can we update it to support Vite 5 so it does not block users' migration?

**Comment by tonyketcham** [comment]
Absolutely! We're working on an upgrade but are blocked by some backwards compatibility issues between the Vite 4.0 and 5.0 Plugin TS type

**Comment by undergroundwires** [comment]
How about bumping the major version on `@modyfi/vite-plugin-yaml` and guide users to right major versions based on which version of Vite they run on `README.md`? I think it would be clear and user-friendly way matching developer expectations if it's not possible to break backwards compatibility.

**Comment by Gotos** [comment]
I saw that someone started publicly working on this as #24 - is there anything else that would help get vite 5 support soon?

**Comment by Gotos** [comment]
I don't mean to bother you, but did you have a chance to look closer at this, @tonyketcham? Or do you have an idea of when you might get around to it?

I understand if working on this isn't your priority right now, I'm just asking so I can plan around it myself. If you don't have the capacity to work on this right now, that's perfectly fine!

**Comment by tonyketcham** [comment]
Apologies for the lengthy delay, totally my fault! I'm planning on having this sorted by the end of this week with a release :)

**Comment by tonyketcham** [comment]
This has been shipped in v1.1.0! 🎉
https://github.com/Modyfi/vite-plugin-yaml/releases/tag/v1.1.0
