### ISSUE TITLE
npm ci gives "only-allow pnpm" but not npm i

### ISSUE THREAD

**Issue by Jwiggiff** [Modyfi/vite-plugin-yaml#7]
I'm trying to setup a github action to deploy my vite site in which I use your plugin. I've been using npm locally and has been working completely fine. However, when I run the github action and run `npm ci` it gives me an error telling me I must use pnpm in this project, even though I use npm locally.

**Comment by tonyduanesmith** [comment]
Just a heads up, I had this issue and noticed the node versions were different. Node 14 I get this issue Node 16 I don't

**Comment by arildm** [comment]
I'm using `yarn install` and I'm also seeing the same difference between Node 14 and 16.

@georgkrause I don't see how changing it to `devPreinstall` could be a good fix. If I understand correctly, only pnpm recognizes that lifecycle script, so it makes the line completely pointless.

**Comment by georgkrause** [comment]
@arildm I don't know what this line is good for anyways, but if only pnpm picks up this line, it at least doesn't make all other package managers not work anymore, while having it in preinstall blocks them all. But I'm fine with another idea, if you have one :)

**Comment by tonyketcham** [comment]
> If I understand correctly, only pnpm recognizes that lifecycle script, so it makes the line completely pointless.
Great point @arildm you're totally right that it'll become useless if it's only detected by pnpm

**Comment by arildm** [comment]
@tonyketcham So what would be a good fix though? Adding that line seems to be disrupting npm and yarn usage. My suggestion would be to remove the line, but I'm not exactly sure what effect that would have.

**Comment by tonyketcham** [comment]
This has been resolved in `v1.0.4`!
